[package]
name = "astra"
version = "0.1.0"
edition = "2021"
license = "MIT"
authors = ["ibraheem <ibrah1440@gmail.com>"]
description = "A synchronous HTTP server built on hyper."
repository = "https://github.com/ibraheemdev/astra"
keywords = ["http", "hyper", "web"]
categories = ["http", "web", "network-programming", "web-programming::http-server"]


[dependencies]
log = "0.4.14"
num_cpus = "1.13.1"
polling = "2.2.0"
tokio = "1.12.0"
futures-core = "0.3.19"
hyper = { version = "0.14.6", features = ["http1", "http2", "server", "stream"] }

[dev-dependencies]
matchit = "0.4.4"
