[package]
name = "hyper-blocking"
version = "0.1.0"
edition = "2018"

[dependencies]
hyper = { version = "0.14.6", features = ["http1", "http2", "server"] }
log = "0.4.14"
num_cpus = "1.13.1"
polling = "2.2.0"
tokio = { version = "1.12.0" }
